In [2]:
import numpy as np
import pandas as pd

In [7]:
arr = np.array([(1,2,3),[4,5,6]])
print(type(arr[0]))

<class 'numpy.ndarray'>


In [8]:
arr.ndim

2

In [9]:
arr.shape

(2, 3)

In [10]:
arr.size

6

In [11]:
arr.dtype

dtype('int64')

In [2]:
np.random.random(5)

array([0.71730085, 0.75275391, 0.02666277, 0.07780859, 0.93343501])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
p_val = np.ptp(a)    # 极差: 3

In [7]:
s_val = np.std(a)    # 方差: 1.12

In [8]:
v_val = np.var(a)    # 方差: 1.25

In [9]:
a = np.random.rand(2,3)
a

array([[0.04328545, 0.34905369, 0.64367142],
       [0.10500008, 0.14320037, 0.57552411]])

In [12]:
a.reshape(3,2)
a

array([[0.04328545, 0.34905369, 0.64367142],
       [0.10500008, 0.14320037, 0.57552411]])

In [13]:
a = np.array([[1, 2], [3, 4]])

In [15]:
a_flat = a.flatten()  # [1, 2, 3, 4]
a_flat

array([1, 2, 3, 4])

In [16]:
a_t = a.T             # [[1, 3], [2, 4]]
a_t

array([[1, 3],
       [2, 4]])

In [18]:
a_flip = np.flip(a)   # [[4, 3], [2, 1]]
a_flip

array([[4, 3],
       [2, 1]])

In [19]:
arr = np.array([10, 20, 30])

In [20]:
arr_app = np.append(arr, [40])    # [10, 20, 30, 40]
arr_app

array([10, 20, 30, 40])

In [21]:
np.append(arr, 40)

array([10, 20, 30, 40])

In [24]:
arr_del = np.delete(arr, 1)       # [10, 30]
arr_del

array([10, 30])

In [25]:
a1 = np.array([[1, 2]])
a2 = np.array([[3, 4]])

In [29]:
print(np.concatenate((a1, a2), axis=0))

[[1 2]
 [3 4]]


In [28]:
print(np.vstack((a1, a2)))

[[1 2]
 [3 4]]


In [30]:
print(np.hstack((a1, a2)))

[[1 2 3 4]]


In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x,y

(array([1, 2, 3]), array([4, 5, 6]))

In [4]:
x-y

array([-3, -3, -3])

In [5]:
np.arange(3)

array([0, 1, 2])

In [6]:
np.arange(3)+5

array([5, 6, 7])

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 0], [0, 1]])

In [9]:
C = np.dot(A, B)      # 矩阵乘法
print(C)

[[1 2]
 [3 4]]


In [10]:
D = A @ B             # 推荐写法，等同np.matmul(A, B)
print(D)

[[1 2]
 [3 4]]


In [16]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [17]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [14]:
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
np.linalg.det(b)

np.float64(-0.49999999999999967)

In [15]:
a @ b

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [2]:
import pandas as pd

In [4]:
print(pd.Series([0.25, 0.5, 0.75, 1.0]))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [6]:
print(pd.Series(5, index=[100, 200, 300]))

100    5
200    5
300    5
dtype: int64


In [7]:
population_dict = {'California': 3833, 'Texas': 1966, 'New York': 1965}
print(pd.Series(population_dict))

California    3833
Texas         1966
New York      1965
dtype: int64


In [10]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

s1 = pd.Series([1,2,3,4,5],index=indA)
s2 = pd.Series([1,2,3,4,5],index=indB)
s1,s2

(1    1
 3    2
 5    3
 7    4
 9    5
 dtype: int64,
 2     1
 3     2
 5     3
 7     4
 11    5
 dtype: int64)

In [11]:
# 交集：提取共同拥有的索引
indC = indA.intersection(indB)         # 返回 Index([3, 5, 7], dtype='int64')
s3 = pd.Series(s1+s2,index=indC)
s3

3    4.0
5    6.0
7    8.0
dtype: float64

In [14]:
# 1. 常规的单/多重条件数值筛选
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
# 筛选出大于15 且 小于45 的值 (注意：多条件必须加括号！)
condition = (s > 15) & (s < 45)
print(condition)

a    False
b     True
c     True
d     True
e    False
dtype: bool


In [16]:
# 1. 由单个Series创建(DataFrame变成只有一列的表)
pop_s = pd.Series({'CA': 3833, 'TX': 1966})
print(pd.DataFrame(pop_s, columns=['population']))

    population
CA        3833
TX        1966


In [18]:
# 2. 由Series组成的字典创建(每个Series变成一列，自动按索引对齐)
area_s = pd.Series({'CA': 423967, 'TX': 695662})
print(pd.DataFrame({'population': pop_s, 'area': area_s}))

    population    area
CA        3833  423967
TX        1966  695662


In [20]:
# 3. 由字典构成的列表创建(每个字典变成一行，键变成列名；缺失的键填入 NaN)
data_list = [{'a': 1, 'b': 2}, {'b': 3, 'c': 4}]
print(pd.DataFrame(data_list))
# 结果中第一行的 'c' 为 NaN，第二行的 'a' 为 NaN

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0


In [3]:
# 4. 由二维 NumPy 数组创建(可人为指定 index 和 columns)
arr = np.random.rand(3, 2)
print(pd.DataFrame(arr, columns=['foo', 'bar'], index=['a', 'b', 'c']))

        foo       bar
a  0.607101  0.972586
b  0.810251  0.496853
c  0.997797  0.984033


In [4]:
s1 = pd.Series([1], index=['a'],name="s1")
s2 = pd.Series([2], index=['b'],name="s2")
s1,s2

(a    1
 Name: s1, dtype: int64,
 b    2
 Name: s2, dtype: int64)

In [6]:
print(pd.DataFrame(s1, s2))

    s1
s2    
2  NaN


In [7]:
print(pd.DataFrame([s1, s2]))

      a    b
s1  1.0  NaN
s2  NaN  2.0


In [4]:
area_s = pd.Series({'CA': 423967, 'TX': 695662})
pop_s = pd.Series({'CA': 3833, 'TX': 1966})
df = pd.DataFrame({'area': area_s, 'population': pop_s})
print(df)

      area  population
CA  423967        3833
TX  695662        1966
